version: "3.1"
services:
  webserver:
    image: nginx:alpine
    container_name: psemla-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8888:80"
    mariadb:
      image: mariadb:10.0
      container_name: psemla-mariadb
      working_dir: /application
      volumes:
        - ./phpdocker/data/mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=app
        - MYSQL_USER=docker
        - MYSQL_PASSWORD=docker
      ports:
        - "8891:3306"
    php-fpm:
      build: ./phpdocker/php
      container_name: php-fpm
      working_dir: /application
      volumes:
        - .:/application

